### PR TITLE
Use personal token dev

### PR DESCRIPTION
**Pull request by fxsalazar**
Just to avoid sharing/using the `GITHUB_CLIENT_SECRET` while dev

### CODE REVIEW

**Review by colebemis — COMMENTED** [review]
Thanks for the PR, @fxsalazar!

I'm a little hesitant to use a different form of authentication in development and production. I'm worried that some things might work in development and not in production (or visa versa) because of different permission scopes between a PAT and an OAuth app. 

As an alternative to sharing a client secret, we include instructions to create your own OAuth app to use for development purposes. That way, we don't share secrets and we still use the OAuth flow in local development. 

I'd love to hear your thoughts on this.

**Comment by fxsalazar** [comment]
I just wanted to reduce the friction (jumping the hoops of asking/waiting for the secret and/or creating the OAuth app) from _project-discovery_ to testing the code. As a dev, you understand why are you using the OAuth app and for me it was just easier to cut to the chase and _inject_ the token.

> I'm a little hesitant to use a different form of authentication in development and production. I'm worried that some things might work in development and not in production (or visa versa) because of different permission scopes between a PAT and an OAuth app. 

Yes, this might/will happen as soon as new api endpoints are used but it would be the same when those are used while using the OAauth app and permissions must be updated. Either way, PRs, unit tests and e2e tests should be the fisrt line of defense to new features. (including testing the login flow)

> As an alternative to sharing a client secret, we include instructions to create your own OAuth app to use for development purposes. That way, we don't share secrets and we still use the OAuth flow in local development.

And yes to this too, this should be included as well, noting that it must include what permissions should be added in the app; which in the end are the same permissions given to the PAT.

**Comment by colebemis** [comment]
I see your points. I can get on board with using a PAT in local development 👍 

I wonder if we can implement it in a simpler way though.

What if we allow folks to store the PAT in the `.env.local` file and reference that when you click the SignInButton? Something like this:

```jsx
function SignInButton() {
  return (
    <Button 
      onClick={async () => {
        // Sign in with a personal access token in local development
        if (import.meta.env.DEV && import.meta.env.VITE_GITHUB_PAT) {
          try {
            const token = import.meta.env.VITE_GITHUB_PAT
            const username = await getUsername(token)
            setGitHubUser({username, token})
          } catch (error) {
            console.error(error)
          }
          return
        }
        
        // Otherwise, sign in with OAuth
        window.location.href = `https://github.com/login/oauth/authorize?client_id=${
          import.meta.env.VITE_GITHUB_CLIENT_ID
        }&state=${
          // URL to redirect to after signing in
          encodeURIComponent(window.location.href)
        }&scope=repo,gist`
      }}
      ...
```

**Review by colebemis — APPROVED** [review]
Thank you, @fxsalazar! 🚀

**Pull request merged**
